### PR TITLE
Added option for setting both screens and cropping

### LINKED ISSUE #11: Add an option to set both home screen and lock screen
It would be useful to have a constant like `WallpaperManager.BOTH`, so we could set both lock screen and home screen in one method call.
I think this may also be a workaround for #6.

### PR DESCRIPTION
**Pull request by ApoorvaAditya**
Fixes #11

### CODE REVIEW

**Comment by ApoorvaAditya** [comment]
I'm not familiar with Java and Native Android development so there is a bit of code duplication and I am not really sure how to use function overloading properly here so please improve this. I've also not checked for errors when the crop integers are negative or something invalid and how that would affect the package.

**Comment by AdityaMulgundkar** [comment]
@ApoorvaAditya Thanks a lot for the PR! I have merged your code into master & I'm testing a few things out in the develop branch before pushing it to live on pub.dev. I'll let you know once I've done that.

**Comment by AdityaMulgundkar** [comment]
@ApoorvaAditya Great job on the implementation! I have pushed your code to live on pub.dev (https://pub.dev/packages/wallpaper_manager), you can check the new features by upgrading/setting the version to 1.0.8.

Thank you so much for this.

**Comment by ApoorvaAditya** [comment]
@AdityaMulgundkar Thanks for the merge! Glad I could contribute. :)

**Pull request merged**
